apiVersion: v1
kind: Service
metadata:
  name: store
  annotations:
    configmanagement.gke.io/namespace-selector: application-namespace-selector
spec:
  selector:
    app: store
  ports:
  - port: 8080
    targetPort: 8080
---
kind: ServiceExport
apiVersion: net.gke.io/v1
metadata:
  name: store
  annotations:
    configmanagement.gke.io/namespace-selector: application-namespace-selector
