kind: RepoSync
apiVersion: configsync.gke.io/v1beta1
metadata:
  name: store-reposync
  annotations:
    configmanagement.gke.io/namespace-selector: application-namespace-selector
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/npintaux/pe-with-gkee-bookstore.git
    branch: main
    auth: none
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: rb-store
  annotations:
    configmanagement.gke.io/namespace-selector: application-namespace-selector
subjects:
- kind: ServiceAccount
  name: ns-reconciler-applications
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io