apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
  name: backend-bookstore
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: backend       # Change the value of this label selector to match different scopes by scope name
      kubernetes.io/metadata.name: bookstore  # Change the value of this label selector to match different namespaces by namespace name
---
kind: RepoSync
apiVersion: configsync.gke.io/v1beta1
metadata:
  name: repo-sync
  annotations:
    configmanagement.gke.io/namespace-selector: backend-bookstore  # Actuate this resource in the namespaces with labels matched by the namespace selector
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/npintaux/pe-with-gkee
    branch: main
    dir: fleet/teams/backend/bookstore
    auth: none
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: be-bookstore
  annotations:
    configmanagement.gke.io/namespace-selector: backend-bookstore  # Actuate this resource in the namespaces with labels matched by the namespace selector
subjects:
- kind: ServiceAccount
  name: ns-reconciler-bookstore
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io