apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
  name: backend-bookstore
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: backend-team
      kubernetes.io/metadata.name: bookstore
