kind: RepoSync
apiVersion: configsync.gke.io/v1beta1
metadata:
  name: repo-sync
  annotations:
    configmanagement.gke.io/namespace-selector: backend-bookstore
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/npintaux/pe-with-gkee-bookstore
    branch: main
    auth: none
