kind: RepoSync
apiVersion: configsync.gke.io/v1beta1
metadata:
  name: repo-sync
  annotations:
    configmanagement.gke.io/namespace-selector: backend-bookstore-scope
spec:
  sourceFormat: unstructured
  git:
    repo: https://github.com/npintaux/pe-with-gkee-bookstore
    branch: main
    auth: none
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: be-bookstore
  annotations:
    configmanagement.gke.io/namespace-selector: backend-bookstore-scope
subjects:
- kind: ServiceAccount
  name: ns-reconciler-bookstore
  namespace: config-management-system
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  annotations:
    configmanagement.gke.io/namespace-selector: backend-bookstore-scope
  name: ns-reconciler-bookstore-role
rules:
# Update 'apiGroups' and 'resources' to reference actual resources managed by 'RepoSync'.
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts", "services"]
  verbs: ["*"]
- apiGroups: ["net.gke.io"]
  resources: ["serviceexports"]
  verbs: ["*"]
