apiVersion: configmanagement.gke.io/v1
kind: NamespaceSelector
metadata:
  name: frontend-scope
spec:
  mode: dynamic
  selector:
    matchLabels:
      fleet.gke.io/fleet-scope: frontend  # Change the value of this label selector to match different scopes by scope name